{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "chatbot-service.fullname" . }}-secrets
spec:
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ .Values.secrets.existingSecret }}
    creationPolicy: Owner
  data:
    - secretKey: API_KEY
      remoteRef:
        key: {{ .Values.externalSecret.remoteRefs.apiKey.key }}
    - secretKey: HF_ACCESS_TOKEN
      remoteRef:
        key: {{ .Values.externalSecret.remoteRefs.hfToken.key }}
    - secretKey: QDRANT_URL
      remoteRef:
        key: {{ .Values.externalSecret.remoteRefs.qdrantUrl.key }}
    - secretKey: QDRANT_API_KEY
      remoteRef:
        key: {{ .Values.externalSecret.remoteRefs.qdrantApiKey.key }}
    - secretKey: RECO_SERVICE_URL
      remoteRef:
        key: {{ .Values.externalSecret.remoteRefs.recoServiceUrl.key }}
    - secretKey: K8S_LOG_LEVEL
      remoteRef:
        key: {{ .Values.externalSecret.remoteRefs.logLevel.key }}
    - secretKey: SLACK_WEBHOOK
      remoteRef:
        key: {{ .Values.externalSecret.remoteRefs.slackWebhook.key }}
{{- end }}
