replicaCount: 1
image:
  tag: "dev"
env:
  NODE_ENV: development
  PORT: 3001
  API_CORE_URL: "http://shopyverse-api-core.dev.svc.cluster.local"
  RECO_SERVICE_URL: "http://shopyverse-reco-service.dev.svc.cluster.local:8002"
secrets:
  existingSecret: chatbot-secrets-dev
