apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chatbot-service.fullname" . }}-config
  labels:
    {{- include "chatbot-service.labels" . | nindent 4 }}
data:
  LOG_LEVEL: {{ .Values.env.LOG_LEVEL | quote }}
  NODE_ENV: {{ .Values.env.NODE_ENV | quote }}
  QDRANT_URL: "http://{{ .Values.externalServices.qdrant.host }}:{{ .Values.externalServices.qdrant.port }}"
