apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chatbot-service.fullname" . }}-secrets
  labels:
    {{- include "chatbot-service.labels" . | nindent 4 }}
type: Opaque
data:
  hf-access-token: {{ .Values.secrets.hfAccessToken | b64enc | quote }}
  api-key: {{ .Values.secrets.apiKey | b64enc | quote }}
  db-password: {{ .Values.secrets.dbPassword | b64enc | quote }}
